name: warta_jemaat
description: Warta Jemaat PDF generator (Mobile A5 + Booklet A4 + Cover A4)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.0
  printing: ^5.13.0
  share_plus: ^10.0.0
  path_provider: ^2.1.4
  media_store_plus: ^0.1.4
  android_intent_plus: ^5.2.1
  image_picker: ^1.1.2
  qr: ^3.0.2
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
